# Generated by Django 6.1 on 2026-08-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentleave',
            old_name='leave_type',
            new_name='Leave_type',
        ),
        migrations.AddField(
            model_name='studentleave',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
