# Generated by Django 6.1 on 2026-08-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_01', '0002_rename_leave_type_studentleave_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentleave',
            name='deleted_time',
            field=models.DateTimeField(null=True),
        ),
    ]
